name: Build and Publish Index

on:
  schedule:
    - cron: '0 6 * * 1' # 每周一 06:00 UTC (北京时间周一下午2点)
  workflow_dispatch: # 允许手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout 当前仓库
      - name: Checkout current repo
        uses: actions/checkout@v4

      # 2. 安装 Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      # 3. 执行 Go 程序
      - name: Run main.go
        run: go run main.go

      # 4. 检查是否生成 domain_tree.html
      - name: Check if domain_tree.html exists
        id: check_file
        run: |
          if [ ! -f domain_tree.html ]; then
            echo "domain_tree.html not found. Exiting with failure."
            exit 1
          fi
          mv domain_tree.html index.html

      # 5. Clone 目标仓库
      - name: Clone target repo
        run: |
          git clone https://github.com/lnbiuc/geosite-tree.git out_repo

      # 6. 拷贝 index.html 到目标仓库
      - name: Copy index.html
        run: |
          cp index.html out_repo/

      # 7. 提交 index.html 到目标仓库
      - name: Commit and push
        run: |
          cd out_repo
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add index.html
          git commit -m "更新 index.html：$(date '+%Y-%m-%d %H:%M:%S')"
          git push https://x-access-token:${{ secrets.TARGET_REPO_TOKEN }}@github.com/lnbiuc/geosite-tree.git HEAD:main
