name: Weekly Geosite Build

on:
  schedule:
    - cron: '0 6 * * 1'  # 每周一 6:00 UTC（北京时间周一下午 2 点）
  workflow_dispatch:      # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repo
        uses: actions/checkout@v4

      - name: Clone domain-list-community repo
        run: |
          git clone --depth=1 https://github.com/v2ray/domain-list-community.git domain-list-community

      - name: Copy data directory into current repo
        run: |
          rm -rf ./data
          cp -r ./domain-list-community/data ./data

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run main.go
        run: go run main.go

      - name: Check if domain_tree.html exists
        run: |
          if [ ! -f domain_tree.html ]; then
            echo "❌ domain_tree.html not found, exiting with failure."
            exit 1
          fi
          mv domain_tree.html index.html

      - name: Clone target repo
        run: |
          git clone https://github.com/lnbiuc/geosite-tree.git out_repo
          cd out_repo

          git checkout main

      - name: Copy index.html to target repo
        run: |
          cp index.html out_repo/

      - name: Auto-commit from out_repo folder
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 更新时间：${{ steps.timestamp.outputs.time }}
          file_pattern: index.html
          branch: main
          commit_user_name: github-actions[bot]
          commit_user_email: github-actions[bot]@users.noreply.github.com
          token: ${{ secrets.TARGET_REPO_TOKEN }}
